### PR TITLE
Use ADC inplace of Service Account if no creds specified

### PR DESCRIPTION
**Pull request by nhoughto**
as per #4

### CODE REVIEW

**Comment by nhoughto** [comment]
bump

**Comment by shmish111** [comment]
@nhoughto did you get anywhere with this, I can't tell if this project is still alive or not? I'm running gradle builds with google cloud build and this project seems exactly what I'm after.

**Comment by nhoughto** [comment]
nope no update, i guess abandoned / low priority?

**Comment by shmish111** [comment]
did you manage to set something up that works for you in place of this? I'm on the search for ideas etc.

**Comment by nhoughto** [comment]
yeah i just forked it, built it, same code as per the PR and just reference a local JAR instead of via maven dependency. Not great but functional.

**Comment by naveenOnarayanan** [comment]
+1 on this by the way!

**Comment by tehlers** [comment]
Thanks for the PR and sorry for the huge delay in merging it.

**Pull request merged**
